### PR TITLE
add .gitattributes to force lf line endings

### PR DESCRIPTION
**Pull request by saddieeiddas**
Have added `.gitattributes` to ensure `lf` line endings

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/CUModSquad/cu-stores/pull/5" target="_blank">ReviewNinja

**Comment by sysrage** [comment]
Test comment.

**Comment by sysrage** [comment]
Another test.

**Comment by sysrage** [comment]
Test comment.

**Comment by sysrage** [comment]
Another test.

**Comment by sysrage** [comment]
Test comment.

**Comment by sysrage** [comment]
Another comment.

**Comment by sysrage** [comment]
Hopefully the last test comment.

**Comment by sysrage** [comment]
Last was not last.

**Comment by sysrage** [comment]
Testing.

**Comment by sysrage** [comment]
Test

**Comment by sysrage** [comment]
Another test.

**Comment by sysrage** [comment]
Hopefully last test.

**Pull request merged**
